---
title: "News Story"
format: html
editor: visual
---

## The experience of embracing an Afro-Latino identity in a society that rejects it

Aisha Cort grew up on a street in Boston where her Cuban-Guyanese family lived next to an Irish-American family. Across the street from them lived a Jamaican American family and just a few houses down lived a Vietnamese and Cape Verdean family. As she waited at the bus stop or walked to the train station as a young girl, Cort was surrounded by a sea of different languages.

Her babysitter was a Black Panamanian woman who spoke Spanish to her every day. 

The people she stood next to at church every Sunday and sang gospel with her were Black Costa Ricans, Black Hondurans and Africans from Nigeria and Ghana. Gospel was sung in English and Spanish to make sure everyone in the church understood and could communicate with one another. Meeting people who looked like her, and didn't look like her, was normal for Cort.

Cort grew up thinking everywhere in the United States was like her diverse Boston neighborhood. Intersectionality existed in every corner of her hometown and made her feel secure in her identity, she said. However, when she left her home in Boston, others didn't seem to understand her Afro-Latina identity the way she did. 

"I grew up in a strong community so I didn't have to defend who I was, everything was reinforced at home," Cort said. "So I guess the challenge came with other people understanding and being patient with them as they try to understand how these supposedly different identities can come together and be one person."

Cort is a Spanish lecturer at Howard University and specializes in Afro-Latino identity. Still, as she navigated into the professional world, she was questioned for being Black and speaking Spanish, she said. People would speak Spanish around her and think that she couldn't understand based on her appearance. 

A [2020 Pew Research Center](https://www.pewresearch.org/fact-tank/2022/05/02/about-6-million-u-s-adults-identify-as-afro-latino/) study found about 6 million Afro-Latino adults live in the United States. They made up about 2% of the U.S. adult population and 12% of the adult Latino population. However, about one in seven Afro-Latinos, or an estimated 800,000 adults, did not identify as Hispanic. Moreover, about three in ten Afro-Latinos said they had been criticized for speaking Spanish in public, compared with about two-in-ten Latinos who did not identify as Afro-Latino. 

"I think we have a very small window for what we accept with Latinidad and being Black and Latino is very hard for people to wrap their heads around," Cort said.

Latin America is one the most ethnically diverse regions in the world and holds about [130 million people of African descent, making up roughly a quarter of the region's total population.](https://perla.princeton.edu/) As African slaves were brought to Latin America during its colonial period, racial and ethnic groups converged, resulting in a mixing pot of Indigenous people, white colonizers and Black people brought as slaves.

Although many people in Latin America are of mixed ethnicity with varying skin complexions, people with lighter skin are viewed at the top of the socioeconomic hierarchy, while those with darker skin are viewed as poorer or at the bottom of the hierarchy. This mindset has carried into the United States as[studies found that 62% of Hispanic adults said having a darker skin color hurts Hispanics' ability to get ahead in the United States today at least a little.](https://www.pewresearch.org/hispanic/2021/11/04/majority-of-latinos-say-skin-color-impacts-opportunity-in-america-and-shapes-daily-life/) Similarly, 59% said having a lighter skin color helps Hispanics get ahead.

"Racism is huge, but because race operates differently in Latin America and Latin American communities, we don't talk about it," Cort said. "It's embedded in our language and the way that we talk to each other, so people don't even realize half the time when they're doing or saying something that is racially insensitive, or that in a U.S. context, it would be considered racist. It's a huge issue."

Cort said she has used her teaching role at a historically Black college to help students grappling with their own identities and to expose students to identities they may not have seen or understood before. Her identity has allowed her to relate to students and help them better understand the Afro-Latino experience, she said. 

Manuel Mendez, the chair for the D.C. Afro-Latino Caucus, said that Afro-Latinos are not represented enough in the Latino community.

"It's been difficult (being Afro-Latino in D.C.) because the white Latino community co-opted Latinidad and have made it so that their broad issues are addressed," Mendez said. "Latinidad only addresses general issues of immigration objectives and general issues of education, it doesn't address issues of indigeneity."

Mendez became the chair of the Caucus in 2016 and has actively worked to improve the quality of life of Afro-Latinos in the community. He said that the Caucus's overall mission is to advocate for and recognize Afro-Latinos. Latinidad, a term that is referenced to include the entire Latino community living in the U.S., fails to address colorism and make Afro-Latinos feel included, Mendez said.

"Latinidad is supposed to encompass an array of folks, the Spanish, the Indigenous and the Black," Mendez said. "It accompanies all of us whether we consider ourselves Black or Indigenous. Why is it that white Latinos are always seen on top? Why don't we have more Indigenous and Black leadership within Latinidad?" 

Mendez also criticized the lack of Afro-Latino leadership within U.S. politics. Political institutions have struggled to recognize Americans who identify as both Latino and Black. For example, Rep. Adriano Espaillat (D-N.Y.) became the nation's first Dominican American and first formerly undocumented member of Congress in 2016, identifying as ["a Latino of African descent.](https://www.axios.com/2022/02/15/adriano-espaillat-black-caucus)" Despite his identifying as both Black and Latino, the Congressional Black Caucus declined to extend him membership, in part because he is also a member of the Latino caucus. 

In other cases, anti-Blackness and colorism can be seen within American politics, Mendez said. Nury Martinez, a Latina politician who was president of the Los Angeles City Council[, resigned in October after a recording was leaked of her saying racist remarks about the Black child of a white council colleague](https://www.nytimes.com/2022/10/12/us/los-angeles-council-nury-martinez-resigns.html). She additionally belittled Indigenous immigrants in the city's Koreatown neighborhood. Mendez said that people who hold leadership roles like Martinez are the people who have the ability to spread ideas and positively impact Latinidad.

"I think white Latinos have a part to play, but I think they occupy too much space in our community," Mendez said. "I think they need to reevaluate the roles that they play. They have to self-reflect about different ways they can show up for Indigenous and Black folks from Latin America."

Tiffanie Arias, the marketing and communications chair of Alianza, said that it wasn't until early college that she began to navigate both her Black and Ecuadorian identity. She joined Alianza, the George Washington University's first and only Afro-Latina organization, in hopes of finding a community.

Arias grew up in Queens, N.Y., and experienced a melting pot of different ethnicities and identities during her upbringing. When she moved to D.C. for school, it proved difficult as she witnessed less diversity within the Latino community, she said. Most Latino people she comes across in D.C. are Salvadorian or Mexican or of predominantly white backgrounds.

"I feel like (living here) has kind of created a sense of 'othering,'" Arias said. "There's a lot of conversations Afro-Latinos are left out of and that's just really intensified on campus and in Washington in general."

The [2021 U.S. Census](https://www.census.gov/quickfacts/DC) reported that 45.8% of people living in D.C. identify as Black, 11.5% identify as Hispanic or Latino and 3% identify as two or more races. While the majority of D.C. residents are Black, the U.S. Census does not provide enough information to distinguish the number of D.C. residents who identify as both Black and Latino. 

Arias said that her biggest struggle as an Afro-Latina has been the stigma against a darker skin complexion. She attributed the colorism to society's admiration of Eurocentric beauty standards, which include being thin, having a fair skin tone, a small nose and long, straight hair. Arias said that growing up, she received comments on the "knots in her hair" and that "she stayed out in the sun for too long."

"There was no support or positivity that came with the Afro-Latina experience," Arias said. "It was like you should try to adapt, rather than you should try and embrace your roots and who you are, and how you look."

Despite the misunderstanding and underrepresentation that comes with being Afro-Latino, Arias said that she loves belonging to two different worlds and embracing both cultures. Being a part of both communities has allowed her to connect with different people and understand her own identity, she said. Growing up in a household that didn't explore the concept of multiple identities, Arias said that joining Alianza helped her embrace all sides of her identity. 

"You can be Latino, but you can also be black," Arias said. "You don't have to choose what community you belong to, and you don't have to tone yourself down for either one. You don't have to feel like you have to make yourself act or look a certain way, you are enough as you are. Embrace your culture, your look, your everything, because that's ultimately what you're taking everywhere you go."

*Back to [Home Page](https://kbrown86.github.io/kyliebrownwebsite/index2.html)*
