# Navigating How to Use Graphic Images During Times of Global Conflict

The Israel-Hamas war has launched a flooding of graphic content via social media, depicting violent imagery of dead children and adults. The distressing content is easily accessible to young users through platforms like Instagram and TikTok. TikTok said it has removed more than 500,000 videos and closed 8,000 livestreams since Hama\'s attack on Oct. 7, according to The New York Times. Cell phones have made it easier than ever to distribute violent imagery, a tool Hamas has utilized to intentionally enact psychological warfare. The Times also reported that while Hamas accounts have been blocked by platforms like Instagram and TikTok (but not Telegram), \"some schools have urged parents to delete their children\'s online accounts to shield them.\" This is not the first time that graphic war imagery has saturated social media. The Russia-Ukraine war showed the world how social media is changing war depiction. With the current conflict in the Middle East, newsrooms continue to debate when using graphic imagery is appropriate, especially in high-pressure situations involving hostages and propaganda. 

The flooding of graphic content from both Israeli and Palestinian users, even when depicting fake or inaccurate information, has demonstrated the power of images and how they can shape one\'s understanding of the world. Editors have to evaluate the value of including a graphic image in a story, unlike social media users. The main benefit of depicting graphic imagery is that it can oftentimes provide the most accurate depiction of war or any other crisis. NYT Jason Farago said that digital images can \"act as information themselves,\" informing the public of the harsh realities of conflict. Not only has this been seen in the Russian-Ukraine war, but images of Europe\'s refugee crisis, the Iraq War and the Boston Marathon bombings have all left powerful and lasting impressions. A clear example of this is when Time Magazine published an image of an Afghan teenager who had her nose and ears cut off by the Taliban, serving as a call to action for Europe\'s refugee crisis. As a result, a study by the Visual Social Media Lab \"found that social media users did change their language after the picture was published---the majority switched from using \"migrant\" to \"refugee,\" and this effect persisted for at least two months.\" 

Moreover, photojournalists, like other journalists, have the civic responsibility of accurately communicating information to the public. Withholding images due to their graphic and disturbing nature could be viewed as not being transparent and truthful. Kelly McBride, Poynter\'s senior vice president, said, \"If there\'s a clear journalistic purpose and you don\'t show it, then you are failing in your primary purpose of informing the public.\" There is also the aspect of the victim. While some victims may be horrified by the thought of their image circulating the world and feel exploited, others have asked photographers to capture their struggle and grief. Fred Ritchin said in his Time article, \"Photographers have often maintained that they feel it necessary to witness and represent the deaths, calamitous injuries and grief that they discover in conflict situations, and in many cases have been asked to do so by those who are its victims.\" An image can expose the horrors of conflict situations and honor those whose lives were affected. Oftentimes, as seen with the Israel-Hamas conflict, innocent civilians are affected.

While graphic images can serve an important purpose, newsrooms must consider the risks that come with them before choosing to publish. One of the main concerns is the easy accessibility for children to view these disturbing images. While violent imagery of the Israel-Hamas war has circulated on social media these past few weeks, a separate issue on its own, newsrooms also play a role in the distribution of disturbing material. Images of dead bodies or videos of explosions can be especially disturbing to young audiences. Claudia Milne, senior vice president of standards and practices at CBS News, said that the television and radio service \"takes into account if children are likely to be watching at the time, and will usually warn the audience if graphic visuals will be shown.\" Another risk is insensitivity to the victims\' families and the feeling of exploiting a victim. Most families would feel devasted viewing such horrific imagery of their loved ones and many may feel uncomfortable with the \"sensationalism\" that can be associated with graphic material. The Guardian\'s head of photography, Roger Tooth, said there are hundreds of images that they would choose not to publish \"because they are either deeply shocking, insensitive to human dignity, would be painful if seen by relatives or friends, or ultimately run the risk of forcing readers to turn away from the story, which would negate the purpose of photojournalism.\" 

Desensitizing readers is also another risk of frequent graphic imagery. While the purpose of these images is often to touch viewers emotionally, readers can become overwhelmed and disconnected, avoiding such images altogether. This is especially a risk with the increase in graphic imagery seen on social media, where there are sometimes no warnings of what will be viewed. CBS News\'s Claudia Milne said, \"We think about our audience and make sure that we don\'t broadcast images that will make them turn away, thereby defeating the purpose of trying to show them what is happening.\" The selection and volume of images are vital to ensure that a newsroom\'s audience is tuned in and willing to pay attention, not psychologically checked out. Editors also have to take extra caution in hostage situations, such as with Hamas. Newsrooms don\'t want to advance a captor\'s agenda or spread their cause. In the case of the Israel-Hamas war, disturbing videos are intentionally being circulated by Hamas.  The footage could be considered propaganda and \"the goal is to avoid providing extremist groups more fuel to use for creating terror,\" Poynter\'s Fernanda Camarena said. This is much easier said than done and journalists are actively working to grapple with the high-pressure situation of appropriately utilizing images.

There are no standard, universal rules in the journalism industry on how to handle sensitive images. The general guideline is that a graphic image should have a clear purpose and add value that wouldn\'t be gained without using it. The purpose also needs to outweigh the risks of publishing the image. Oftentimes, the value of the image isn\'t fully visible until the editorial process. A photojournalist should always capture an image if they see any potential value from it. However, there is an important distinction between capturing and distributing the image. Gary Knight, co-founder of the VII Photo Agency, said, \"If you\'re performing that role as a photographer or journalist, as some sort of witness or commentator, I think you need to record those things. But I don\'t think that they need to be published.\" The important step that journalists and editors need to include before publishing an image is deliberation or the editorial process. Editors should discuss what value the photo adds and weigh the pros and cons of including it. Moreover, editors should guide with empathy when making this decision and consider how the image may affect others.

 If a news organization chooses to include a graphic image, other tools can be used to avoid possible exploitation of a victim or cause harm to others. For example, CBS News blurs the faces of individuals killed if their faces are visible. There should also always be a warning before displaying the image, to give viewers and readers a choice. Graphic images shouldn\'t be used repeatedly or used as wallpaper or headlines as that takes away the choice from readers. That is one of the key components journalists need to give readers: the decision to view a graphic image using their own free will. Sometimes this is not always possible, especially with live broadcasting; however, if possible, journalists should make their best effort to warn their audience of disturbing content. Context with graphic material is also important to offer accurate information and an explanation. Photojournalist Bradley Secker said, \"As long as the image captions are accurate and the image itself hasn\'t been manipulated, there is little room for propaganda.\" Descriptive image captions can help readers better understand what they are looking at. 

A well-selected image can offer insight into global conflicts that words alone cannot. By utilizing caution and editing tools, journalists can avoid as much harm as possible that may be caused by graphic images. Even so, it is sometimes impossible for journalists to predict the outcome of their work and the effect it may have on people. Additionally, graphic images may not always serve an important enough purpose. The Israel-Hamas war is a prime example of journalists having to make tough decisions on what images should be depicted, and the heavy weight these images carry. The impact of a graphic image can outweigh the risks, but oftentimes it does not. Editors must use their best judgment and empathy to continue to navigate the Israel-Hamas war.

### References 

Camarena, F. (2023). How standards editors are sorting through graphic images from Israel and Gaza. Retrieved from 

<https://www.poynter.org/reporting-editing/2023/how-standards-editors-choose-images-from-israel-and-gaz>

Farago, J. (2023). When Everyone Becomes a War Photographer. Retrieved from 

<https://www.nytimes.com/2023/10/12/arts/design/war-photos-israel-gaza.html> 

Graphic content: when photographs of carnage are too upsetting to publish. (2014). Retrieved from [https://www.theguardian.com/world/2014/jul/23/graphic-content-photographs-too-upsetti ng-to-publish-gaza-mh17-ukraine](https://www.theguardian.com/world/2014/jul/23/graphic-content-photographs-too-upsetting-to-publish-gaza-mh17-ukraine)

Hsu, T. (2023). A New Report Documents How Easily Children Can Access Graphic Images of the War. Retrieved from	<https://www.nytimes.com/2023/10/18/business/media/children-israel-war-tiktok-instagram.html>

 Lewis \@helenlewis, H., & Lewis, H. (2022). How Newsrooms Handle Graphic Images of Violence. Retrieved from	<https://niemanreports.org/articles/how-newsrooms-handle-graphic-images-of-violence/> 

Back to [*Home Page*](https://kbrown86.github.io/kyliebrownwebsite/)
